language: node_js
node_js:
- '6'
deploy:
  provider: s3
  access_key_id: AKIAJRUAFJDMBFPNZRNQ
  secret_access_key:
    secure: rLZLdVCpeNumx6I4v6lEMfczYH1iDP9k2YuiToskRchn/Z2U94d1/GcNaowC3vT2+N4xvPj3E9EJbi4KhSOJArh+TseaZwgWRYssi/jhedTOLEjLOS0+ENzM+r6QTs5ZxS9u0UnUyaNwAHJehSohv2O14S6WkBaJuvYi4wdmfMZrN2bDmVRP6lfV55VvWyIb83BVog74zUPNQH6ak+xKC3kDDwBLCy3GV5nD5rLRbBX0zeR56z88RtFUxJlY3ubzvqYc01ivhkC6BxVQVoE8NTsijQKqiJPEHs+pBxNpaMMxjsQq4Mef6RLp32x0xWfvw8efR0MCVLmKtNbXyxjFPkbSYhuvpQfiAIs2omLaW7wHg2jqlZKlQkMyWIyO6fWMqQ6vBgOBUzv6cxOx5hHvMGVduJRkUEAVw19xXiuNzA8DTuKtO1TFOaGT63syJpdcC4xek50BiXPIi0AhEr3pJijP0MdUy8Wo8DfBU7QXb/7FFsGKk4+fpdD6ORebVVX2RZf+OwgUcAM4jGRpqxOIs4pk8hUg78c5Xe1gg1Xk5m3SKpgsFO0rL2gE09yt6hl1+O2pS7n7vkPRTYiVRPFO9qZ5/WEzUk6N1ZtgpUJ7p4xrWD4x3RftUtFNQ4crQGW4w+JXkKcS0GNEQ7lo/QUIuZzjcwxJPW8l0YhIPPfTxi8=
  bucket: peppermile.com
  local-dir: build
  on:
    repo: astralfrontier/peppermile.org
